### PR TITLE
updated dir name and package checksum

### PR DESCRIPTION
**Pull request by marsmee**

### CODE REVIEW

**Comment by bionade24** [comment]
I only accept PRs with the right sources, [as described in the project of this organisation.](https://github.com/orgs/ros-melodic-arch/projects) The sources the old maintainer specified are shit and not working correctly, so this PR doesn't fix. Please use the official ROS melodic releases.

**Comment by jwhendy** [comment]
@bionade24 Could we add a reference to the project you mention? For example,

- basic reference of setting the source to `git+https` vs. a tarball (at least I assume you want it from git source every time vs. a release snapshot from git?)

- the AUR packages (and ros-gbp) split out meta packages. `roswtf` is part of [ros-comm](https://github.com/ros/ros_comm). I've only seen this splitting done when there is an upstream sub-package (like those from ros-gbp). What is the proper way to construct the `PKGBUILD` header re. upstream, provides, etc. with these sub-packages?

I think expanding the project further than just a sentence would help many people contribute in the way you envision.

**Comment by bionade24** [comment]
> @bionade24 Could we add a reference to the project you mention? For example,
> 
>     * basic reference of setting the source to `git+https` vs. a tarball (at least I assume you want it from git source every time vs. a release snapshot from git?)+
I wan't to definately use tarball releases. Git releases are much to unstable, nothing you want to work with. But when they don't change their release packaging, I'll maybe write some scripts to easier update all packages.
> 
>     * the AUR packages (and ros-gbp) split out meta packages. `roswtf` is part of [ros-comm](https://github.com/ros/ros_comm). I've only seen this splitting done when there is an upstream sub-package (like those from ros-gbp). What is the proper way to construct the `PKGBUILD` header re. upstream, provides, etc. with these sub-packages?
I have no idea if this split has senth and will inform me a bit before making a decision. Until then I would try to extract only the needed parts out of the tarball, shouldn't be much more effort.
> 
> 
> I think expanding the project further than just a sentence would help many people contribute in the way you envision.
I'll try to write a longer guideline.

**Comment by marsmee** [comment]
> I only accept PRs with the right sources, [as described in the project of this organisation.](https://github.com/orgs/ros-melodic-arch/projects) The sources the old maintainer specified are shit and not working correctly, so this PR doesn't fix. Please use the official ROS melodic releases.

I'm sorry, I didn't see that.

Unfortunately I don't have the time to adjust the pull requests at the moment. With the old sources it still worked a few days ago, there were only errors because of wrong checksum and non-existent folders.

**Comment by bionade24** [comment]
Solved with https://github.com/ros-melodic-arch/ros-melodic-roswtf/commit/bd36771a3e980ccbd9f27420f16255776f3234df

**Pull request closed without merging**
